from selenium.webdriver.common.by import By
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
import time


USER = input("enter username: ")
PASS = input("enter password: ")

drive_service = Service(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=drive_service)
driver.get("https://www.roblox.com/login")
options = webdriver.ChromeOptions()
options.add_argument("disable-blink-features=AutomationControlled")
options.add_argument("disable-infobars")
options.add_argument("disable-dev-shm-usage")
options.add_argument("no-sandbox")
options.add_experimental_option("excludeSwitches" , ["enable-automation"])
driver.maximize_window()

user_input = driver.find_element(By.ID, "login-username")
user_input.send_keys(f"{USER}")
pass_input = driver.find_element(By.ID, "login-password")
pass_input.send_keys(f"{PASS}")
driver.find_element(By.ID, "login-button").click()
time.sleep(5)

if (driver.find_element(By.ID, "HomeContainer").is_displayed()):
    time.sleep(1)
    driver.find_element(By.ID, "nav-profile").click()
    time.sleep(2)
    FOLLOWING = driver.find_element(By.XPATH, "(//span)[72]").text
    time.sleep(2)
    n = eval(FOLLOWING)/18
    time.sleep(1)
    driver.find_element(By.ID, "nav-friends").click()
    time.sleep(1)
    driver.find_element(By.ID, "following").click()
    for x in range(round(n)):
        time.sleep(3)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[2]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[3]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[4]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[5]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[6]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[7]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[8]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[9]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[10]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[11]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[12]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[13]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[14]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[15]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[16]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[17]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-more'])[18]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//a[normalize-space()='Unfollow'])[1]").click()
        time.sleep(.1)
        driver.find_element(By.XPATH, "(//span[@class='icon-right'])[1]").click()